# Basic
title: 崔鹏飞
subtitle: Apple Dev
#welcome_message: 
description: 嗨，我是崔鹏飞，一名 iOS 开发小学生。
creator: <a href="https://github.com/githubError">@githubError</a>

url: "http://www.cuipengfei.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'http://www.cuipengfei.cn/resumes/resumes2018.pdf'}
    - {title: 导航, description: 常用网址导航, url: 'http://www.cuipengfei.cn/123.html'}
    #- {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    youyan: cuipengfei
    #disqus: onevcat
    # duoshuo:
# Social
social:
    #weibo: cuipengfei
    github: githubError
    twitter: 0x00ffee
    mail: 0x00ffee@gmail.com


# Baidu Analytics
baidu_analytics: 68ee30beb4d6d80c7b20fff177545e7d    #from //hm.baidu.com/hm.js?***


# Google Analytics
google_analytics: UA-117740493-1

